version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq-kinetique'
    restart: unless-stopped
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672" # Management console port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:17
    container_name: postgres-kinetique
    restart: unless-stopped
    environment:
      POSTGRES_MULTIPLE_DATABASES: Kinetique_Appointment,Kinetique_Nfz,Kinetique_Main
      POSTGRES_USER: kinetique_user
      POSTGRES_PASSWORD: kinetique
    ports:
      - "5432:5432" # PostgreSQL default port
    volumes:
      - postgres_data:/var/lib/postgresql/data

  appointmentService:
    image: kinetique/appointment.api
    container_name: AppointmentsService
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./appointments/Kinetique.Appointment.API/Dockerfile
    depends_on:
      - rabbitmq
      - postgres
      - mainService
    ports:
      - "5675:5675"
    environment:
      ASPNETCORE_URLS: http://+:5675
      ASPNETCORE_ENVIRONMENT: Production

  mainService:
    image: kinetique/main.api
    container_name: MainService
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./main/Kinetique.Main.API/Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    ports:
      - "5161:5161"
    environment:
      ASPNETCORE_URLS: http://+:5161
      ASPNETCORE_ENVIRONMENT: Production

  nfzService:
    image: kinetique/nfz.api
    container_name: NfzService
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./nfz/Kinetique.Nfz.API/Dockerfile
    depends_on:
      - rabbitmq
      - postgres
      - mainService
    ports:
      - "5020:5020"
    environment:
      ASPNETCORE_URLS: http://+:5020
      ASPNETCORE_ENVIRONMENT: Production

  scheduleService:
    image: kinetique/schedule.api
    container_name: ScheduleService
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./schedule/Kinetique.Schedule/Dockerfile
    depends_on:
      - mainService
    ports:
      - "5197:5197"
    environment:
      ASPNETCORE_URLS: http://+:5197
      ASPNETCORE_ENVIRONMENT: Production

volumes:
  postgres_data:
