@appointmentHost = http://localhost:5675/api
@mainHost = http://localhost:5161/api
@scheduleHost = http://localhost:5197/api


### Create appointment
@pesel = 93884383756

### 0.1 Add Patient if not existing
POST {{mainHost}}/patient
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Kowalski 2",
  "phoneNumber": "+48777888555",
  "address": "Random adress 2/5",
  "gender": 1,
  "pesel": "{{pesel}}"
}


### 0.2 Add Doctor if not exists
POST {{mainHost}}/doctor
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "Nowak",
  "gender": 1,
  "licence": "000444"
}

### 0.21 Get Doctors list
GET {{mainHost}}/doctor
Content-Type: application/json


### 1.1 Get Patient by Pesel
GET {{mainHost}}/patient/pesel/{{pesel}}
Content-Type: application/json


### 1.2 Get Doctor
GET {{mainHost}}/doctor/1
Content-Type: application/json

################################
######### APPOINTMENT ##########
################################


### set DoctorId
@doctorCode = 000444

### 2.1 Add Cycle without appointment
POST {{appointmentHost}}/appointment/cycle/
Content-Type: application/json

{
  "limit": 10,
  "patientId": 8,
  "doctorId": 1
}

### 2.2 Get Cycle list
GET {{appointmentHost}}/appointment
Content-Type: application/json

### 2.2.1 Get Cycle by Id
GET {{appointmentHost}}/appointment/cycle/2
Content-Type: application/json

### 2.3 Add Referral to cycle ( for patient )
POST {{appointmentHost}}/appointment/referral
Content-Type: application/json

{
  "uid": "000113",
  "code": "someCode 2",
  "pesel": {"value": "93884383756"},
  "createdOn": "2025-01-15T18:52:18.855Z"
}

### 2.3.1 Add Appointment to cycle
POST {{appointmentHost}}/appointment
Content-Type: application/json

{
  "doctorCode": "{{doctorCode}}",
  "cycleId": 2,
  "startDate": "2025-01-28T10:00:00Z",
  "duration": "00:30:00",
  "description": "Test 123 Laser"
}

### 2.3.2 Remove Appointment
DELETE {{appointmentHost}}/appointment/12
Content-Type: application/json


### 2.4 Remove Referral from Cycle
DELETE {{appointmentHost}}/appointment/referral/2
Content-Type: application/json



################################
########### SCHEDULE ###########
################################


### 2.5 GetSlots for Doctor for period
GET {{scheduleHost}}/schedule/{{doctorCode}}
Content-Type: application/json

### 2.5.1 Create Slots for Doctor for period
POST {{scheduleHost}}/schedule/slot
Content-Type: application/json

{
  "doctorCode": "{{doctorCode}}",
  "startDate": {
    "value": "2025-01-27T00:00:00Z"
  },
  "endDate": {
    "value": "2025-01-31T00:00:00Z"
  },
  "slots": [
    {
      "day": 1,
      "startTime": "10:00:00",
      "endTime": "10:30:00"
    },
    {
      "day": 1,
      "startTime": "10:30:00",
      "endTime": "11:00:00"
    },
    {
      "day": 1,
      "startTime": "11:00:00",
      "endTime": "11:30:00"
    },
    {
      "day": 2,
      "startTime": "10:00:00",
      "endTime": "10:30:00"
    },
    {
      "day": 2,
      "startTime": "10:30:00",
      "endTime": "11:00:00"
    },
    {
      "day": 2,
      "startTime": "11:00:00",
      "endTime": "11:30:00"
    }
  ]
}