// <auto-generated />
using System;
using System.Collections.Generic;
using Kinetique.Nfz.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kinetique.Nfz.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kinetique.Nfz.Model.PatientProcedure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppointmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PatientProcedures");
                });

            modelBuilder.Entity("Kinetique.Nfz.Model.SettlemenetProcedure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Points")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SettlemenetProcedures");
                });

            modelBuilder.Entity("Kinetique.Nfz.Model.StatisticProcedureGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<List<string>>("Codes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("PatientProcedureId")
                        .HasColumnType("bigint");

                    b.Property<long>("SettlemenetProcedureId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PatientProcedureId");

                    b.HasIndex("SettlemenetProcedureId");

                    b.ToTable("StatisticProcedureGroups");
                });

            modelBuilder.Entity("Kinetique.Nfz.Model.StatisticProcedureGroup", b =>
                {
                    b.HasOne("Kinetique.Nfz.Model.PatientProcedure", null)
                        .WithMany("Procedures")
                        .HasForeignKey("PatientProcedureId");

                    b.HasOne("Kinetique.Nfz.Model.SettlemenetProcedure", "SettlemenetProcedure")
                        .WithMany("StatisticProcedures")
                        .HasForeignKey("SettlemenetProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SettlemenetProcedure");
                });

            modelBuilder.Entity("Kinetique.Nfz.Model.PatientProcedure", b =>
                {
                    b.Navigation("Procedures");
                });

            modelBuilder.Entity("Kinetique.Nfz.Model.SettlemenetProcedure", b =>
                {
                    b.Navigation("StatisticProcedures");
                });
#pragma warning restore 612, 618
        }
    }
}
